blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://github.com/ncoderz/awa/security/advisories/new
    about: Report security issues privately via email
